### ISSUE TITLE
Absolute path within --command is not working as expected

### ISSUE THREAD

**Issue by veics** [Netcentric/apply-server#3]
providing the absolute path to a script within --command option is not working as expected, instead is doing a combination between --destination + absolute path within --command

**Comment by veics** [comment]
in addition tot his, is it possible to provide a command in double quotes? eg: --command /hitme="/bin/sudo -u user /path/to/script"

**Comment by ghenzler** [comment]
@veics You can quote commands like `--command /hitme="/path/to/script.sh param1 param2 param3"`. The first part is meant to be a script that runs with the same user as apply-server itself. You can do fancy things in this script, but always double-check what you make available from this "external http trigger".

> providing the absolute path to a script within --command option 

I tested this and it worked, please provide a more detailed example if the problem persists.

**Comment by ghenzler** [comment]
Please re-open if thee problem persists.
