### ISSUE TITLE
Example Script for Apache HTTPD

### ISSUE THREAD

**Issue by kwin** [Netcentric/apply-server#8]
It would be helpful if the readme would contain one script for checking and restarting Apache HTTPD after a new config has been extracted.
I guess the steps are simply
1. `apachectl configtest`
1. `apachectl graceful`

But it would be interesting how to properly deal with errors (i.e. configtest not successful).

**Comment by ghenzler** [comment]
Added documentation: https://github.com/Netcentric/apply-server#using-apply-server-with-apache-httpd
